force-app/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{0000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app-v2/integration-framework/objects/Integration_Log__c/fields/Callout_Class__c.field-meta.xml
<CustomField>
    <fullName>Callout_Class__c</fullName>
    <label>Callout Class</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Callout_Duration__c.field-meta.xml
<CustomField>
    <fullName>Callout_Duration__c</fullName>
    <description>Callout duration in milliseconds</description>
    <label>Callout Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/integration-framework/objects/Integration_Log__c/fields/Endpoint_URL__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_URL__c</fullName>
    <description>Callout endpoint URL</description>
    <label>Endpoint URL</label>
    <type>Url</type>
</CustomField>

force-app-v2/integration-framework/objects/Integration_Log__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>Error message</description>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/integration-framework/objects/Integration_Log__c/fields/Request_Body__c.field-meta.xml
<CustomField>
    <fullName>Request_Body__c</fullName>
    <description>Text body of callout request</description>
    <label>Request Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/integration-framework/objects/Integration_Log__c/fields/Response_Body__c.field-meta.xml
<CustomField>
    <fullName>Response_Body__c</fullName>
    <description>Text body of callout response</description>
    <label>Response Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/integration-framework/objects/Integration_Log__c/fields/Response_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Response_Status_Code__c</fullName>
    <description>Callout response status code</description>
    <label>Response Status Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/integration-framework/objects/Integration_Log__c/fields/Success__c.field-meta.xml
<CustomField>
    <fullName>Success__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if callout executed successfully</description>
    <label>Success</label>
    <type>Checkbox</type>
</CustomField>

force-app-v2/integration-framework/classes/core/IFI_CalloutsExecutor.cls
/**
 * Class used to execute callout implementations.
 *
 * @author: Melikyan Ed
 * @date: 19.04.2023
 *
 */
public class IFI_CalloutsExecutor {
    private static List<Integration_Log__c> logs = new List<Integration_Log__c>();
    private static IFI_CalloutsExecutor instance;
    private static final List<Integer> SUCCESS_STATUS_CODES = new List<Integer>{ 200, 201 };
    private Map<String, String> hiddenParams = new Map<String, String>();

    private IFI_CalloutsExecutor() {
    }

    public static IFI_CalloutsExecutor getInstance() {
        if (instance == null) {
            instance = new IFI_CalloutsExecutor();
        }
        return instance;
    }

    public Object execute(IFI_InterfaceCallout callout) {
        Object executionResult;
        HttpRequest request = initHttpRequest(callout);
        Integration_Log__c log = initLog(callout);
        Datetime startDT = Datetime.now();
        try {
            executionResult = processRequest(callout, request, log);
        } catch (Exception e) {
            handleResponseException(e, log);
        } finally {
            log.Callout_Duration__c = System.now().getTime() - startDT.getTime();
        }
        return executionResult;
    }

    public void saveLogs() {
        insert logs;
        logs = new List<Integration_Log__c>();
    }

    public List<Integration_Log__c> getLogs() {
        return logs;
    }

    private HttpRequest initHttpRequest(IFI_InterfaceCallout callout) {
        HttpRequest request = new HttpRequest();
        String endPoint = callout.getEndpointURL();
        String httpMethod = callout.getHTTPMethod();
        request.setEndpoint(endPoint);
        request.setMethod(httpMethod);
        request.setTimeout(callout.getTimeout());
        request.setHeader('Content-Type', 'text/xml; charset=UTF-8');
        request.setHeader('SOAPAction', 'Wololo');
        return request;
    }

    private Integration_Log__c initLog(IFI_InterfaceCallout callout) {
        Integration_Log__c log = new Integration_Log__c(
            Callout_Class__c = callout.getType().toString(),
            Endpoint_URL__c = callout.getEndpointURL(),
            Success__c = true
        );
        logs.add(log);
        return log;
    }

    private Object processRequest(IFI_InterfaceCallout callout, HttpRequest request, Integration_Log__c log) {
        String requestBody = callout.buildRequestBody();
        requestBody = replaceSecuredParams(requestBody, callout.getHiddenParams());
        request.setBody(requestBody);
        HttpResponse response = sendRequest(callout, request, log);
        if (SUCCESS_STATUS_CODES.contains(response.getStatusCode())) {
            Object parsedResponse = callout.parseResponseBody(response.getBody());
            log.Success__c = true;
            log.Request_Body__c = replaceSecuredParams(
                requestBody.mid(0, Integration_Log__c.Request_Body__c.getDescribe().length),
                callout.getHiddenParams()
            );
            return parsedResponse;
        } else {
            log.Request_Body__c = requestBody;
            log.Error_Message__c = response.getStatus();
            log.Success__c = false;
        }
        return null;
    }

    private HttpResponse sendRequest(IFI_InterfaceCallout callout, HttpRequest request, Integration_Log__c log) {
        Http http = new Http();
        HttpResponse response = http.send(request);
        log.Response_Status_Code__c = response.getStatusCode();
        log.Response_Body__c = response.getBody();
        return response;
    }

    private String replaceSecuredParams(String requestBody, Map<String, String> hiddenParams) {
        String result = requestBody;
        for (String param : hiddenParams.keySet()) {
            result = result.replaceAll(param, Matcher.quoteReplacement(hiddenParams.get(param)));
        }
        return result;
    }

    private void handleResponseException(Exception e, Integration_Log__c log) {
        Datetime endLog = Datetime.now();
        String errorMessage = e.getMessage() + ' ' + e.getStackTraceString();
        log.Error_Message__c = e.getMessage();
        log.Success__c = false;
    }
}